blogs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('', RedirectView.as_view(url=' main/', permanent=True))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('account/registration/', views.registration, name='registration'),
    path('account/login/', views.MainLoginView.as_view(), name='login'),
    path('account/logout/', views.logout_view, name='logout'),
    path('account/profile/', views.profile, name='profile'),
    path('account/profile/edit/', views.EditProfileView.as_view(), name='edit-profile'),
    path('account/profile/delete/', views.DeleteProfileView.as_view(), name='delete-profile'),
    path('create_post/', views.create_post, name='create-post'),
    path('post/<int:pk>/edit_post/', views.edit_post, name='edit-post'),
    path('post/<int:pk>/delete_post/', views.DeletePost.as_view(), name='delete-post'),
    path('post/<int:pk>/add_comment/', views.add_comment, name='add-comment'),
    path('post/<int:pk>/toggle_like/', views.toggle_like, name='toggle_like'),
    path('comment/<int:pk>/edit_comment/', views.edit_comment, name='edit-comment'),
    path('comment/<int:pk>/delete_comment/', views.delete_comment, name='delete-comment'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from blogs import settings


class MyUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', null=True, blank=False)
    bio = models.TextField()

class Post(models.Model):
    MyUser = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post_content = models.TextField(default='')
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="liked_posts", blank=True)

class Comment(models.Model):
    comment_text = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    my_user = models.ForeignKey(MyUser, on_delete=models.CASCADE)

main/forms.py
from django import forms
from main.models import MyUser, Post
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
import re
User = get_user_model()

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="пароль", widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="пароль (повторно)", widget=forms.PasswordInput)
    username = forms.CharField(label="никнейм", help_text='')

    class Meta:
        model = MyUser
        fields = ('username', 'password', 'password_confirm', 'avatar', 'bio')
        labels = {'username': 'никнейм', 'password': 'пароль', 'password_confirm': 'пароль (повторно)', 'avatar': 'аватарка', 'bio': 'расскажите о себе'}

        error_messages = {
            'username': {
                'unique': "пользователь с таким логином уже зарегистрирован",
            },
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and not re.fullmatch(r"^[a-zA-z_0-9]+$", username):
            raise forms.ValidationError("логин должен содержать только латиницу, нижнее подчеркивание и цифры")
        return username

    def clean(self):
        super().clean()
        if self.cleaned_data.get('password') != self.cleaned_data.get('password_confirm'):
            raise ValidationError({'password_confirm': 'пароли не совпадают'})
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class EditProfileForm(forms.ModelForm):
    username = forms.CharField(label="никнейм", help_text='')
    class Meta:
        model = MyUser
        fields = ('username', 'avatar', 'bio')
        labels = {'username': 'никнейм', 'avatar': 'аватарка', 'bio': 'расскажите о себе'}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_content']
        labels = {'post_content': 'содержание поста'}


class CommentForm(forms.Form):
    comment_text = forms.CharField(required=True, label="комментарий")
    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from main.forms import RegistrationForm, PostForm, EditProfileForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.utils import timezone
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import UpdateView
from django.db.models import Count
from main.models import Post, MyUser, Comment
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import DeleteView
from django.urls import reverse


def index(request):
    return render(request, 'basic.html')


class MainLoginView(LoginView):
    template_name = 'login.html'
    def get_success_url(self):
        return reverse('main:index')


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:index')
    else:
        form = RegistrationForm()
    return render(request, 'registration.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('main:index')


@login_required
def profile(request):
    user_posts = Post.objects.filter(MyUser=request.user).order_by('-pub_date').annotate(
        comment_count=Count('comment'),
        like_count=Count('likes'))
    context = {'post_list': user_posts,}
    return render(request, 'profile.html', context)


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = MyUser
    template_name = 'edit_profile.html'
    form_class = EditProfileForm
    success_url = reverse_lazy('main:profile')

    def get_object(self, queryset=None):
        return self.request.user


class DeleteProfileView(LoginRequiredMixin, DeleteView):
    model = MyUser
    template_name = 'delete_profile.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            Post = form.save(commit=False)
            Post.MyUser = request.user
            Post.pub_date = timezone.now()
            Post.save()
            return redirect('main:index')
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form, })


class PostListView(generic.ListView):
    model = Post
    paginate_by = 3
    template_name = 'index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.order_by('-pub_date')[:50].annotate(
            comment_count=Count('comment', distinct=True),
            like_count=Count('likes', distinct=True))


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect(reverse('main:index'))
        else:
            return render(request, 'edit_post.html', {'form': form, 'post': post})
    else:
        form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form, 'post': post})


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('main:index')
    template_name = "delete_post.html"

    def test_func(self):
        obj = self.get_object()
        return obj.MyUser == self.request.user

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.image:
            self.object.image.delete(save=False)
        return super().delete(request, *args, **kwargs)


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data.get('comment_text')
            Comment.objects.create(
                post=post,
                comment_text=comment_text if comment_text else '',
                my_user=request.user
            )
            return redirect('main:index')
        else:
            pass
    else:
        form = CommentForm()
    context = {'post': post, 'form': form,}
    return render(request, 'add_comment.html', context)


@login_required
def edit_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.user != comment.my_user:
        return redirect('main:index')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment.comment_text = form.cleaned_data['comment_text']
            comment.save()
            return redirect('main:index')
    else:
        form = CommentForm(initial={'comment_text': comment.comment_text})

    context = {'form': form, 'comment': comment}
    return render(request, 'edit_comment.html', context)


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user != comment.my_user:
        return redirect('main:index')
    if request.method == 'POST':
        comment.delete()
        return redirect('main:index')
    return redirect('main:index')


@login_required
def toggle_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    if user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return redirect('main:index')

main/templates/add_comment.html
{% extends "basic.html" %}
{% block content %}
    <h2>новый комментарий</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">отправить</button>
    </form>
{% endblock %}

main/templates/basic.html
<!doctype html>
<html lang="ru">
<head>
    {% block title %}<title>модный сайтик</title>{% endblock %}
    <meta charset="utf-8"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}"/>
</head>
<body>
    <div class="container">
        {% block sidebar %}
            <ul class="nav">
                <a href="{% url 'main:index' %}">главная</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'main:profile' %}">профиль</a>
                    <a href="{% url 'main:edit-profile' %}">редактировать профиль</a>
                    <a href="{% url 'main:delete-profile' %}">удалить профиль</a>
                    <a href="{% url 'main:logout' %}">выйти из профиля</a>
                    <a href="{% url 'main:create-post' %}">создать пост</a>
                {% else %}
                    <a href="{% url 'main:login' %}">вход</a>
                    <a href="{% url 'main:registration' %}">регистрация</a>
                {% endif %}
            </ul>
        {% endblock %}
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

main/templates/create_post.html
{% extends "basic.html" %}
{% block content %}
    <h2>новый пост</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">опубликовать</button>
    </form>
{% endblock %}

main/templates/delete-post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/delete_post.html
{% extends "basic.html" %}
{% block content %}
    <h2>удаление поста</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">удалить</button>
    </form>
{% endblock %}

main/templates/delete_profile.html
{% extends "basic.html" %}
{% block content %}
    <h2>удаление пользователя {{ object.username }}</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">удалить</button>
    </form>
{% endblock %}

main/templates/edit_comment.html
{% extends "basic.html" %}
{% block content %}
    <h2>редактирование комментария</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">сохранить изменения</button>
    </form>
{% endblock %}

main/templates/edit_post.html
{% extends "basic.html" %}
{% block content %}
    <h2>редактирование поста</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">сохранить изменения</button>
    </form>
{% endblock %}

main/templates/edit_profile.html
{% extends "basic.html" %}
{% block content %}
    <h2>изменение информации {{ user.username }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">сохранить</button>
    </form>
{% endblock %}

main/templates/index.html
{% extends "basic.html" %}
{% block content %}
    {% if post_list %}
        {% for p in post_list %}
            <div class="post">
                <p><strong>содержание поста: {{ p.post_content }}</strong></p>
                <p>автор: {{ p.MyUser }}</p>
                <p>опубликовано: {{ p.pub_date|date:"d.m.Y H:i" }}</p>
                <div class="statistics">
                    <p>количество комментариев: {{ p.comment_count }}</p> <span> | </span>
                    <p>количество лайков: {{ p.like_count }}</p>
                </div>
                {% if request.user == p.MyUser %}
                    <div class="actions-w-post">
                        <a href="{% url 'main:edit-post' pk=p.id %}">редактировать пост</a> <span> | </span>
                        <a href="{% url 'main:delete-post' pk=p.id %}">удалить пост</a>
                    </div>
                {% endif %}

                <p><strong>комментарии:</strong></p>
                {% for comment in p.comment_set.all %}
                    <p>{{ comment.my_user.username }}: {{ comment.comment_text }}</p>

                    <div class="actions-w-com">
                        {% if request.user == comment.my_user %}
                            <a href="{% url 'main:edit-comment' pk=comment.id %}">редактировать</a>
                            <form action="{% url 'main:delete-comment' pk=comment.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="удалить" class="button"/>
                            </form>
                        {% endif %}
                    </div>
                {% empty %}
                    <p>прокомментируйте этот пост первым</p>
                {% endfor %}

                {% if user.is_authenticated %}
                <a href="{% url 'main:toggle_like' pk=p.pk %}">
                    {% if request.user in p.likes.all %}
                        убрать лайк
                    {% else %}
                        поставить лайк
                    {% endif %}
                </a>

                <a href="{% url 'main:add-comment' pk=p.id %}">написать пару ласковых</a>
                {% else %}
                <p>зарегистрируйтесь или войдите в аккаунт чтобы что? ставить лайки и писать комментарии</p>
                {% endif %}
            </div>
        {% endfor %}

        {% if is_paginated %}
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                {% endif %}
            </div>
        {% endif %}

    {% else %}
        <p>пусто :(</p>
    {% endif %}
{% endblock %}

main/templates/login.html
{% extends "basic.html" %}
{% block content %}
    <h2>вход в аккаунт</h2>
    <form method="post" action="{% url 'main:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">войти</button>
    </form>
{% endblock %}

main/templates/logout.html
{% extends "basic.html" %}
{% block content %}
  <p>вы вышли из аккаунта :(</p>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">выйти</button>
  </form>
{% endblock %}

main/templates/profile.html
{% extends "basic.html" %}
{% block content %}
    <h2>профиль {{ user.username }}</h2>
    {% if user.bio %}
    {% endif %}
    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="аватарка" width="200" height="200">
    {% else %}
        <p>здесь аватарка (не найдено)</p>
    {% endif %}
    <p>инфа о пользователе: {{ user.bio }}</p>

    {% if post_list %}
        {% for p in post_list %}
            <div class="post">
                <p><strong>содержание поста: {{ p.post_content }}</strong></p>
                <p>автор: {{ p.MyUser }}</p>
                <p>опубликовано: {{ p.pub_date|date:"d.m.Y H:i" }}</p>
                <div class="statistics">
                    <p>количество комментариев: {{ p.comment_count }}</p> <span> | </span>
                    <p>количество лайков: {{ p.like_count }}</p>
                </div>
                {% if request.user == p.MyUser %}
                    <div class="actions-w-post">
                        <a href="{% url 'main:edit-post' pk=p.id %}">редактировать пост</a> <span> | </span>
                        <a href="{% url 'main:delete-post' pk=p.id %}">удалить пост</a>
                    </div>
                {% endif %}

                <a href="{% url 'main:toggle_like' pk=p.pk %}">
                    {% if request.user in p.likes.all %}
                        убрать лайк
                    {% else %}
                        поставить лайк
                    {% endif %}
                </a>

                <p><strong>комментарии:</strong></p>
                {% for comment in p.comment_set.all %}
                    <p>{{ comment.my_user.username }}: {{ comment.comment_text }}</p>

                    <div class="actions-w-com">
                        {% if request.user == comment.my_user %}
                            <a href="{% url 'main:edit-comment' pk=comment.id %}">редактировать</a>
                            <form action="{% url 'main:delete-comment' pk=comment.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="удалить" class="button"/>
                            </form>
                        {% endif %}
                    </div>
                {% empty %}
                    <p>прокомментируйте этот пост первым</p>
                {% endfor %}
                <a href="{% url 'main:add-comment' pk=p.id %}">написать пару ласковых</a>
            </div>
        {% endfor %}

        {% if is_paginated %}
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                {% endif %}
            </div>
        {% endif %}
    {% else %}
        <p>посты не найдены</p>
    {% endif %}
{% endblock %}

main/templates/registration.html
{% extends "basic.html" %}
{% block content %}
    <h2>регистрация</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">зарегистрироваться</button>
    </form>
{% endblock %}